services:
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_DB: jobberDev
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432' 
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    ports:
      - '4000:4000'
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
     interval: 30s
     timeout: 10s
     retries: 3
    depends_on:
    - postgres
    